---
title: "Lab 1: Algebra"
author: "Maximiliano Garnier Villarreal"
lang: es
toc: true
toc-depth: 3
toc-title: Contenidos
number-sections: true
highlight-style: pygments
theme: sandstone
format:
  html:
    embed-resources: true
    code-fold: true
    code-summary: "Codigo"
    code-tools: true
    html-math-method: katex
  pdf: 
    prefer-html: false
  docx: default
execute:
  warning: false
  error: false
  echo: true
---

# Algebra

## Vectores

Para sumar (`+`), restar (`-`) o multiplicar (`*`) vectores elemento por elemento o para el producto punto (`%*%`) recordar que se requiere que los vectores tengan la misma dimension.

```{r}
(a = 1:20)          # numeros enteros consecutivos
(b = seq(0,20,4))   # numeros del 0 al 20 cada 4
(c = seq(30,50,4))
(d = seq(50,20,-5)) # numeros del 50 al 20 cada 5 (decreciente)
(e = rep(12,8))     # numero 12 repetido 8 veces
(f = c(1,3,5,7))    # numeros cualquiera

a * 5
a + 5
b * c
b %*% c
```

## Matrices

Para matrices recordar que para sumar o restar deben tener las mismas dimensiones y para multiplicar (`%*%`) deben cumplir $A(m,n) \cdot B(n,p)$

```{r}
matrix(data = 1:9,nrow = 3,ncol = 3)
matrix(data = 1:15,nrow = 3)
matrix(data = 1:15,ncol=3,byrow=TRUE)

A = matrix(c(1,3,5,7),nrow = 2,byrow = F)
A

det(A)    # determinante de matriz
eigen(A)  # eigen values y vectors de A
solve(A)  # inversa de A
t(A)      # transpuesta de A

A[1,]       # fila 1, todas las columnas (todas las columnas)
A[2,1]      # fila 2, columna 1 (1 elemento)
A[2,1] = 15 # reemplaza el elemento en fila 2 columna 1 por 15
A


(B = matrix(data = c(11,13,15,17),nrow = 2,byrow = F))
  
A + B   # suma de matrices
A %*% B # multiplicacion de matrices
A %*% c(2,5) # multplicacion de matriz y vector
 
datos <- rio::import("data/ABOC.csv")
 
(C = as.matrix(datos)) # convierte dataframe en matriz
```
