---
title: "Lab 7: Estadistica Inferencial - Pruebas 1"
author: "Maximiliano Garnier Villarreal"
output:
  html_notebook:
    highlight: pygments
    number_sections: yes
    theme: flatly
    toc: yes
  word_document:
    toc: yes
  pdf_document:
    df_print: kable
    keep_tex: yes
    number_sections: yes
    toc: yes
  html_document:
    df_print: paged
    highlight: textmate
    keep_md: yes
    number_sections: yes
    theme: spacelab
    toc: yes
always_allow_html: yes
---

```{r setup, include=FALSE, warning=F, message=FALSE}
library(MOTE)
library(papaja)
library(GMisc) # para intervalos de confianza
library(OneTwoSamples) # para intervalos y pruebas
library(DescTools) # para pruebas
library(rstatix) # pruebas y tamanho efecto
library(effectsize) # para tamanho del efecto
library(itns) # para tamanho del efecto
library(broom)
library(tidyverse)
```


# Prueba $\chi^2$ de 1 varianza

$$H_0 : \sigma^2 = \sigma_0^2$$

```{r}
set.seed(4101)
w = rnorm(n = 10, mean = 1, sd = 0.2)
var_test1(x = w, sigma2 = 0.2^2, side = 0) # OneTwoSample
var_test1(x = w, sigma2 = 0.5^2, side = 0) # OneTwoSample
VarTest(x = w, sigma.squared = 0.5^2,conf.level = .95) # DescTools
interval_var1(x = w) # OneTwoSample
ci_chisq(s = sd(w), n = length(w),digits = 4) # GMisc
```


# Prueba F de 2 varianzas

$$H_0 : \sigma_1^2 = \sigma_2^2$$

$$H_0 : \frac{\sigma_1^2}{\sigma_2^2} = 1$$

```{r}
set.seed(4101) 
x = rnorm(n = 12, mean = 20, sd = 4)
y = rnorm(n = 10, mean = 20, sd = 5)
var.test(x,y,ratio = 1,alt = "two.sided",conf = 0.95)
var_test2(x,y,side = 0) # OneTwoSample
interval_var2(x,y) # OneTwoSample
ci_F(s1 = sd(x), n1 = length(x), s2 = sd(y), n2 = length(y)) # GMisc
```


# Prueba Z de 1 muestra

$$H_0 : \mu = \mu_0$$

```{r}
# Ho: mu=13
mu = 13
sig = 4
n = 8

set.seed(4101)
x = rnorm(n = n,mean = 10,sd = sig)

(z = (mean(x)-mu)/(sig/sqrt(length(x))))
(zcrit = c(qnorm(0.025), qnorm(0.975)))

ci_z(x = mean(x), sig = sig, n = length(x), conf.level = .95) # GMisc

z1 = ZTest(x, mu=mu, sd_pop = sig, conf.level = .95) # DescTools
z1
z1 %>% tidy()

mean_test1(x, mu=mu, sigma = sig) # OneTwoSamples
interval_estimate1(x, sigma = sig) # OneTwoSamples

d.z.mean(mu = mu, m1 = mean(x), sig = sig, 
         sd1 = sd(x), n = n, a = .05)[1:3] %>% 
  as_tibble_row() # MOTE
```



# Prueba t de 1 muestra

$$H_0 : \mu = \mu_0$$

```{r}
# Ho: mu=7
mu = 7

verm = c(6.1, 5.5, 5.3, 6.8, 7.6, 5.3, 6.9, 6.1, 5.7)

t1 = t.test(x = verm, mu=mu, alt = "two.sided", conf = 0.95)
t1
t1 %>% tidy()

(tcrit = c(qt(0.025,length(verm)-1),qt(0.975,length(verm)-1)))

t.mod = lm(verm~1)
t.mod %>% 
  tidy(conf.int=T,conf.level=.95)

d.single.t(m = mean(verm), u = mu, sd = sd(verm), 
           n = length(verm), a = .05)[1:3] %>% 
  as_tibble_row() # MOTE

cohens_d(verm, mu = mu, ci = .95) # effectsize

hedges_g(verm, mu = mu, ci = .95) # effectsize
```


# Prueba t de 2 muestras independientes

$$H_0 : \mu_1 = \mu_2$$

```{r}
# Ho: Diferencia en medias = 0
A = c(25, 40, 34, 37, 38, 35, 29, 32, 35, 44, 27, 33, 37, 38, 36)
B = c(45, 37, 36, 38, 49, 47, 32, 41, 38, 45, 33, 39, 46, 47, 40)

DF = tibble(Val=c(A,B), Grp=c(rep(c('A','B'),each=length(A))))

DF %>% 
  ggplot() + 
  geom_boxplot(aes(Grp,Val,col=Grp)) + 
  theme_bw()

DF %>% 
  ggplot(aes(Grp,Val,col=Grp)) + 
  stat_summary(geom = 'pointrange',
               fun.data = mean_cl_boot,
               fun.args = list(conf.int=.95)) + 
  theme_bw()

DF %>% 
  group_by(Grp) %>% 
  get_summary_stats(type = 'mean_sd')

var.test(A,B,conf.level = .95)

t.test(A, B, mu=0,conf.level = .95) %>% 
  tidy()

t.test(B, A, mu=0,conf.level = .95) %>% 
  tidy()

t.test(A, B, mu=0,conf.level = .95, var.equal = T) %>% 
  tidy()

t.test(Val~Grp,DF,conf.level = .95)

ci_t2(x1 = mean(A), s1 = sd(A), n1 = length(A), 
      x2 = mean(B), s2 = sd(B), n2 = length(B), 
      conf.level = .95) # GMisc

ti.mod = lm(Val~Grp,DF)
ti.mod  %>% 
  tidy(conf.int=T,conf.level=.95)

cohens_d(A, B, ci = .95, pooled_sd = T)

hedges_g(A, B, ci = .95, pooled_sd = T)

d.ind.t(m1 = mean(A), m2 = mean(B), 
        sd1 = sd(A), sd2 = sd(B), 
        n1 = length(A), n2 = length(B), a = .05)[1:3] %>% 
  as_tibble_row() # MOTE
g.ind.t(m1 = mean(A), m2 = mean(B), 
        sd1 = sd(A), sd2 = sd(B), 
        n1 = length(A), n2 = length(B), a = .05)[1:3] %>% 
  as_tibble_row() # MOTE
```


# Prueba t de 2 muestras dependientes

$$H_0 : \mu_D = \mu_{despues} - \mu_{antes} = 0$$

```{r}
# Ho: Media de diferencia = 0
Antes = c(13.5,14.6,12.7,15.5,11.1,16.4,13.2,19.3,16.7,18.4)
Despues = c(13.6,14.6,12.6,15.7,11.1,16.6,13.2,19.5,16.8,18.6)

boxplot(Despues,Antes)

t.test(Despues,Antes,mu=0,paired = T) %>% 
  tidy()

cohensd_rm(Despues, Antes) # itns

# MOTE
d.dep.t.avg(m1 = mean(Antes),m2 = mean(Despues),
            sd1 = sd(Antes),sd2 = sd(Despues),
            n = length(Antes),a = .05)[1:3] %>% 
  as_tibble_row()

d.dep.t.diff(mdiff = mean(Antes-Despues),sddiff = sd(Antes-Despues),
             n = length(Antes),a = .05)[1:3] %>% 
  as_tibble_row()

d.dep.t.rm(m1 = mean(Antes),m2 = mean(Despues),
           sd1 = sd(Antes),sd2 = sd(Despues),
           r = cor(Antes,Despues),n = length(Antes),
           a = .05)[1:3] %>% 
  as_tibble_row()


ci_t(x = mean(Despues-Antes), s = sd(Despues-Antes), 
     n = length(Antes), conf.level = .95) # GMisc

lm((Despues-Antes)~1) %>% 
  tidy(conf.int=T,conf.level=.95)
```


# Prueba t de correlacion

$$H_0 : r = 0$$

```{r}
alfa = .1
a = c(8,16,12,13,16,14,16,11,15,13)
b = c(7,8,10,12,14,9,13,6,9,10)
c = c(3,5,9,5,5,8,13,3,9,9)

cordat = tibble(a,b,c)

cor.test(a,b,method = "pearson",conf = 0.90) %>% 
  tidy()

CorCI(rho = cor(a,b), n = length(a), conf.level = 0.90) # DescTools

correlation::cor_test(cordat,'a','b',
                      method = 'pearson',
                      ci = 1-alfa)
```



