---
title: "Lab 1: Algebra"
author: "Maximiliano Garnier Villarreal"
output:
  html_document:
    df_print: paged
    highlight: textmate
    keep_md: yes
    number_sections: yes
    theme: spacelab
    toc: yes
  word_document:
    toc: yes
  pdf_document:
    df_print: kable
    keep_tex: yes
    number_sections: yes
    toc: yes
always_allow_html: yes
---

# Algebra

```{r setup, include=FALSE}
library(rio)
```


## Vectores

Para sumar (`+`), restar (`-`) o multiplicar (`*`) vectores elemento por elemento o para el producto punto (`%*%`) recordar que se requiere que los vectores tengan la misma dimension.

```{r}
(a = 1:20)          # numeros enteros consecutivos
(b = seq(from = 0,to = 20,by = 4))   # numeros del 0 al 20 cada 4
(c = seq(from = 30,to = 50,by = 4))
(d = seq(from = 50,to = 20,by = -5)) # numeros del 50 al 20 cada 5 (decreciente)
(e = rep(12,8))     # numero 12 repetido 8 veces
(f = c(1,3,5,7))    # vector de datos con c()

(a = 1:20)          # numeros enteros consecutivos
(b = seq(0,20,4))   # numeros del 0 al 20 cada 4
(c = seq(30,50,4))
(d = seq(50,20,-5)) # numeros del 50 al 20 cada 5 (decreciente)
(e = rep(12,8))     # numero 12 repetido 8 veces

a * 5
a + 5
b * c
b %*% c
```


## Matrices

Para matrices recordar que para sumar o restar deben tener las mismas dimensiones y para multiplicar (`%*%`) deben cumplir $A(m,n) \cdot B(n,p)$

```{r}
matrix(data = 1:9,nrow = 3,ncol = 3)
matrix(data = 1:15,nrow = 3)
matrix(data = 1:15,ncol=3,byrow=TRUE)
?matrix   # ayuda sobre funcion matrix

A = matrix(f,nrow = 2,byrow = F)
A

det(A)    # determinante de matriz
eigen(A)  # eigen values y vectors de A
solve(A)  # inversa de A
t(A)      # transpuesta de A

A[1,]       # fila 1, todas las columnas (todas las columnas)
A[2,1]      # fila 2, columna 1 (1 elemento)
A[2,1] = 15 # reemplaza el elemento en fila 2 columna 1 por 15
A


(B = matrix(data = c(11,13,15,17),nrow = 2,byrow = F))
  
A + B   # suma de matrices
A %*% B # multiplicacion de matrices
A %*% c(2,5) # multplicacion de matriz y vector
 
datos <- import("data/ABOC.csv")
 
(C = as.matrix(datos)) # convierte dataframe en matriz
```



 